version: '3.5'

volumes:
  web-dependencies:

networks:
  web-frontend:
    name: shopping-app
    driver: bridge
    external: true

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - web-frontend
    ports:
      - 3001:3000