'use client'

import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import ProgressBarProvider from "@/providers/ProgressBarProvider";
import { ToastContainer } from "react-toastify";
import { usePathname } from 'next/navigation'

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Shopping App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname()

  return (
    <html lang="en">
      <body className={pathname == '/login' ? 'page-login' : ''}>
        <AuthProvider>
          <ProgressBarProvider>{children}</ProgressBarProvider>
        </AuthProvider>
        <ToastContainer autoClose={true} />
      </body>
    </html>
  );
}
